#!groovy
node {
  stage('Preparation') {
    git 'https://github.com/hstreb/tdc-poa-2016.git'
  }
  stage('Compile') {
    dir('project') {
      sh "./gradlew clean compileJava"
    }
  }
  stage('Unit test') {
    dir('project') {
      sh "./gradlew test jacoco"
    }
  }
  stage('Build') {
    dir('project') {
      sh "./gradlew build -PcurrentBuild=$BUILD_NUMBER"
    }
  }
  stage('Publish to Artifactory') {
    dir('project') {
      sh "./gradlew artifactoryPublish -PcurrentBuild=$BUILD_NUMBER -PartifactoryUrl=http://artifactory:8081"
    }
  }
  stage('SonarQube') {
    dir('project') {
      sh "./gradlew sonar -PcurrentBuild=$BUILD_NUMBER -Dsonar.host.url=http://sonarqube:9000"
    }
  }
  stage('Results') {
    dir('project') {
      junit 'build/**/TEST-*.xml'
      publishHTML (target: [
          allowMissing: false,
          alwaysLinkToLastBuild: false,
          keepAll: true,
          reportDir: 'build/reports/jacoco/test/html/',
          reportFiles: 'index.html',
          reportName: "Jacoco Report"
          ])
    }
  }
}
