artifactory:
  image: jfrog-docker-reg2.bintray.io/jfrog/artifactory-oss
  ports:
    - "8081:8081"
  environment:
    - ARTIFACTORY_HOME='/var/opt/jfrog/artifactory'
  volumes:
    - ./artifactory/data:$ARTIFACTORY_HOME/data
    - ./artifactory/logs:$ARTIFACTORY_HOME/logs
    - ./artifactory/backup:$ARTIFACTORY_HOME/backup
postgresql:
  image: orchardup/postgresql:latest
  environment:
    - POSTGRESQL_USER=sonar
    - POSTGRESQL_PASS=sonar
    - POSTGRESQL_DB=sonar
  volumes:
    - ./db/sonarqube/:/var/lib/postgresql
  ports:
    - "5432:5432"
sonarqube:
  image: sonarqube
  links:
    - postgresql
  environment:
    - SONARQUBE_JDBC_USERNAME=sonar
    - SONARQUBE_JDBC_PASSWORD=sonar
    - SONARQUBE_JDBC_URL=jdbc:postgresql://postgresql/sonar
  ports:
    - "9000:9000"
    - "9092:9092"
    - "443"
jenkins:
  image: jenkins
  ports:
    - "8082:8080"
    - "50001:50001"
  links:
    - artifactory
    - sonarqube
